# FROM, ARG, ENV, COPY, RUN, CMD, ENTRYPOINT, VOLUME, WORKDIR, LABEL - Giving your image properties

LABEL version = "1.0.0"
LABEL author = "Anne Otieno"
LABEL year = "2022"
LABEL random = "QWERTY"

FROM python:3.9-alpine 

RUN echo "Hello From Docker"
